# Introduktion til NumPy

[Numpy](https://numpy.org/doc/stable/index.html) er et Python-bibliotek til oprettelse og manipulation af matricer, den primære datastruktur, der bruges af maskinlæringsalgoritmer. [Matricer](https://da.wikipedia.org/wiki/Matrix_(matematik)) er matematiske objekter, der bruges til at gemme værdier i rækker og kolonner. I kender dem nok fra mange andre sprog og strukturen i en SQL database. Derfor er det også nemt at få data fra en central SQL-database og bruge det til machinelearning.

I Python kaldes matricer *lists*, NumPy kalder dem *arrays*, og TensorFlow kalder dem *tensors*. Python repræsenterer matricer med datatypen [liste](https://docs.python.org/3/library/stdtypes.html#lists).

NumPy er et stort bibliotek som bruges i flere grene, vi kommer ikke til at gå i dybden med NumPy, men vi skal have en grundlæggende forståelse for at kunne bruge det til resten af vores 10 dages ML kursus.

Mange af operationerne kender I nok fra andre sprog, men så har I også muligheden for at vende jer lidt til Python syntaxen


## Import NumPy module

Vi skal installere NumPy modulet for at kunne bruge det senere

In [1]:
import numpy as np

## Populate arrays with specific numbers

Skriv `np.array` for at lave en NumPy array, med værdi som du selv vælger. Her er et eksempel med `np.array` som laver en 8-elementer langt en dimensionelt array:

In [2]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


Du kan også bruge `np.array` til at oprette en todimensionel matrix. For at oprette en todimensionel matrix skal du angive en ekstra lag af firkantede parenteser. For eksempel opretter følgende kald en 3x2 matrix:

In [3]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


For at udfylde en matrix rene nuller, kald `np.zeros`. For at udfylde en matrix med rene ettere, kald `np.ones`.


## Udfyld arrays med sekvenser af tal

Du kan udfylde et array med en sekvens af tal:


In [6]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]
[]


Bemærk, at `np.arange` genererer en sekvens, der inkluderer den nedre grænse (5), men ikke den øvre grænse (12).
Altså [5,12)


## Udfyld arrays med tilfældige tal

NumPy giver forskellige funktioner til at udfylde arrays med tilfældige tal inden for visse intervaller. For eksempel genererer `np.random.randint` tilfældige heltal mellem en lav og en høj værdi. Følgende kald udfylder et array med 6 elementer med tilfældige heltal mellem 50 og 100.




In [101]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
random_integers_between_two_dimensional_50_and_100 = np.random.randint(low=50, high=101, size=(6,6))
print(random_integers_between_50_and_100)
print(random_integers_between_two_dimensional_50_and_100)

[76 70 69 53 69 59]
[[ 86  80  73  81  83  90]
 [ 82  94  55  65  81  64]
 [ 52  55  86  66  57  84]
 [100  55  89  88  56  90]
 [ 81  70  97  78  72  53]
 [ 80  64  62  55  53  73]]


Bemærk, at det højeste genererede heltal ved brug af `np.random.randint` er én mindre end argumentet `high`.


For at oprette tilfældige decimaltal mellem 0.0 og 1.0, kald `np.random.random`. For eksempel:

In [65]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1)

[0.50588121 0.57675137 0.69076754 0.04661093 0.72605691 0.36731195]


## Matematiske operationer på NumPy-operand

Hvis du ønsker at lægge to arrays sammen eller trække dem fra hinanden, kræver lineær algebra, at de to operander har de samme dimensioner. Derudover, hvis du ønsker at multiplicere to arrays, pålægger lineær algebra strenge regler for den dimensionelle kompatibilitet af operanderne. Heldigvis bruger NumPy en teknik kaldet [**broadcasting**](https://developers.google.com/machine-learning/glossary/#broadcasting) til at virtuelt udvide den mindre operand til dimensioner, der er kompatible med lineær algebra. For eksempel bruger følgende operation broadcasting til at tilføje 2.0 til værdien af hvert element i arrayet, der blev oprettet i den foregående kodecelle:


In [66]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.50588121 2.57675137 2.69076754 2.04661093 2.72605691 2.36731195]


Den følgende operation afhænger også af broadcasting for at multiplicere hvert element i et array med 3:


In [69]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[300 300 300 300 297 300]


## Opgave 1: Opret et lineært datasæt

Dit mål er at oprette et simpelt datasæt bestående af en enkelt funktion (feature) og en etiket (label) som følger:

1. Tildel en sekvens af heltal fra 6 til 20 (inklusiv) til et NumPy-array kaldet `feature`.
2. Tildel 15 værdier til et NumPy-array kaldet `label` på følgende måde:

```
   label = (3)(feature) + 4
```
For eksempel skal den første værdi for `label` være:

```
  label = (3)(6) + 4 = 22
 ```

In [106]:
feature = np.random.randint(6,20) # write your code here
print(feature)
label = np.random.randint((feature*3) + 4, size=15)  # write your code here
print(label)

19
[18  8 26  7 22  2 49 21 14  5  1 45 24 36 31]


In [116]:
#@title Double-click to see a possible solution to Task 1.
feature = np.arange(6, 21)
print(feature)
label = (feature * 3) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


## Opgave 2: Tilføj lidt støj til datasættet

For at gøre dit datasæt lidt mere realistisk, skal du indsætte lidt tilfældig støj i hvert element i det `label`-array, du allerede har oprettet. Præcist sagt, skal du ændre hver værdi, der er tildelt `label`, ved at tilføje en *forskellig* tilfældig decimalværdi mellem -2 og +2.

Stol ikke på broadcasting. Opret i stedet et `noise`-array med samme dimension som `label`.


In [125]:
#googlede mig til random.uniform fordi kunne ikke finde en måde at gøre det på, i de tilligere exempler vi har fået
#at bruge random.uniform at omkring 80% hurtigtere
noise = np.random.uniform(low=-2, high=2, size=9999999)    # write your code here
#noise = (np.random.random([9999999]) * 4) - 2
print(noise)
#label = label + noise    # write your code here
#print(label)

[-0.16108264  0.27604727 -1.98480917 ... -0.12960923 -1.1637278
  0.19014099]


In [121]:
#Løsning til Task 2

noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise
print(label)

[-1.81691427  1.05555389  0.10585317 -0.95290527 -0.21264739  1.55978325
  0.78416983 -0.97838335 -0.00991038  1.87015115  0.45239159  1.0542678
 -1.50272964 -1.97048152 -0.71744094]
[21.90228499 30.63239857 32.10669715 28.51677039 33.35192714 41.77650529
 40.06187808 42.37771661 46.75948217 55.12126561 52.26835327 62.1612457
 56.31985137 63.61335712 68.94063869]
